In [1]:
import numpy as np
a=np.array([[1,4,2],[5,6,7],[8,9,10]])
print(a)
print(np.sum(a))
print(np.sum(a,axis=1))

[[ 1  4  2]
 [ 5  6  7]
 [ 8  9 10]]
52
[ 7 18 27]


In [2]:
print(a)

[[ 1  4  2]
 [ 5  6  7]
 [ 8  9 10]]


In [6]:
b=np.array([1,2,4])
a-b

array([[ 0,  2, -2],
       [ 4,  4,  3],
       [ 7,  7,  6]])

In [7]:
a-b.T

array([[ 0,  2, -2],
       [ 4,  4,  3],
       [ 7,  7,  6]])

In [8]:
b.T

array([1, 2, 4])

In [9]:
print(np.sum(a,axis=0))

[14 19 19]


In [1]:
b

NameError: name 'b' is not defined

In [2]:
a

NameError: name 'a' is not defined

In [4]:
a

array([[ 1,  4,  2],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [5]:
a[1,:]

array([5, 6, 7])

In [8]:
a[1,:].argpartition(1)

array([0, 1, 2], dtype=int64)

In [9]:
b=[3,1,2,0]

In [10]:
b

[3, 1, 2, 0]

In [11]:
b.argpartition

AttributeError: 'list' object has no attribute 'argpartition'

In [17]:
np.array(b).argsort()

array([3, 1, 2, 0], dtype=int64)

In [18]:
b=np.array(b)

In [19]:
b

array([3, 1, 2, 0])

In [20]:
b.argsort()

array([3, 1, 2, 0], dtype=int64)

In [21]:
b+4

array([7, 5, 6, 4])

In [22]:
b.argsort()

array([3, 1, 2, 0], dtype=int64)

In [23]:
b

array([3, 1, 2, 0])

In [24]:
b=b+4


In [25]:
b.argsort()

array([3, 1, 2, 0], dtype=int64)

In [26]:
b

array([7, 5, 6, 4])

In [27]:
np.argpartition(b,2)

array([3, 1, 2, 0], dtype=int64)

In [28]:
b

array([7, 5, 6, 4])

In [4]:
b=np.split(a,3
    )

In [5]:
b

[array([[1, 4, 2]]), array([[5, 6, 7]]), array([[ 8,  9, 10]])]

In [6]:
b.shape

AttributeError: 'list' object has no attribute 'shape'

In [7]:
np.reshape(b,(-1,3))

array([[ 1,  4,  2],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [16]:
c=np.array([1,4,5,6,7,8])

In [17]:
c

array([1, 4, 5, 6, 7, 8])

In [18]:
d=np.split(c,2)

In [19]:
d

[array([1, 4, 5]), array([6, 7, 8])]

In [26]:
d[0].shape

(3,)

In [22]:
np.reshape(d,(2,3))

array([[1, 4, 5],
       [6, 7, 8]])

In [23]:
d

[array([1, 4, 5]), array([6, 7, 8])]

In [25]:
d[0].shape

(3,)

In [3]:
a[(1,2),(2,0)]

array([7, 8])

In [4]:
a

array([[ 1,  4,  2],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [2]:
a\

array([[ 1,  4,  2],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [4]:
np.random.choice(a,3)

ValueError: 'a' must be 1-dimensional

In [9]:
ind=np.random.choice(4,4,replace=False)

In [51]:

np.append(b,[a[i] for i in (ind-1)],axis=0)


ValueError: all the input arrays must have same number of dimensions

In [34]:
c=np.array(b)

In [39]:
ind

array([0, 3, 1, 2])

In [43]:
(print(a[i] for i in ind)
    

SyntaxError: unexpected EOF while parsing (<ipython-input-43-71bb2b3a968e>, line 2)

In [38]:
c.reshape(-1,1)

array([[<generator object <genexpr> at 0x0000000005D451B0>]], dtype=object)